In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/cannabis-strains/cannabis.csv


In [2]:
data = pd.read_csv("/kaggle/input/cannabis-strains/cannabis.csv")

In [3]:
data.head()

Strain    Type  Rating                                     Effects  \
0          100-Og  hybrid     4.0  Creative,Energetic,Tingly,Euphoric,Relaxed   
1  98-White-Widow  hybrid     4.7    Relaxed,Aroused,Creative,Happy,Energetic   
2            1024  sativa     4.4   Uplifted,Happy,Relaxed,Energetic,Creative   
3        13-Dawgs  hybrid     4.2     Tingly,Creative,Hungry,Relaxed,Uplifted   
4        24K-Gold  hybrid     4.6   Happy,Relaxed,Euphoric,Uplifted,Talkative   

                      Flavor  \
0        Earthy,Sweet,Citrus   
1      Flowery,Violet,Diesel   
2    Spicy/Herbal,Sage,Woody   
3  Apricot,Citrus,Grapefruit   
4       Citrus,Earthy,Orange   

                                         Description  
0  $100 OG is a 50/50 hybrid strain that packs a ...  
1  The ‘98 Aloha White Widow is an especially pot...  
2  1024 is a sativa-dominant hybrid bred in Spain...  
3  13 Dawgs is a hybrid of G13 and Chemdawg genet...  
4  Also known as Kosher Tangie, 24k Gold is a 60%...

In [4]:
data.describe()

Rating
count  2351.000000
mean      4.310634
std       0.836394
min       0.000000
25%       4.200000
50%       4.400000
75%       4.700000
max       5.000000

In [5]:
print(data["Flavor"].isnull().values.sum())
data["Flavor"] = data["Flavor"].fillna("None")

46


In [6]:
total_flavor = []
max_len = 0
total_flavor.append("None")
for val in data["Flavor"].values:
    print(val)
    val = val.split(",")
    
    if len(val) > max_len:
        max_len = len(val)
    
    for f in val:
        if f not in total_flavor:
            total_flavor.append(f)
            

Earthy,Sweet,Citrus
Flowery,Violet,Diesel
Spicy/Herbal,Sage,Woody
Apricot,Citrus,Grapefruit
Citrus,Earthy,Orange
None
Earthy,Sweet,Pungent
Citrus,Pungent,Earthy
Earthy,Woody,Flowery
Earthy,Grape,Sweet
Pine,Diesel
Earthy,Pine,Skunk
Earthy,Woody,Pine
Earthy,Woody,Pungent
Citrus,Earthy,Pine
Earthy,Diesel,Flowery
None
Earthy,Sweet,Berry
Earthy,Pungent,Berry
Citrus,Pungent,Sweet
Diesel,Pepper,Earthy
Earthy,Woody,Citrus
Earthy,Pine,Woody
Earthy,Pungent,Woody
Earthy,Pungent,Citrus
Menthol,Blue,Cheese,Chemical
Earthy,Pine,Diesel
Earthy,Sweet,Pungent
Earthy,Diesel,Spicy/Herbal
Earthy,Sweet,Woody
Earthy,Mango,Lemon
Lemon,Diesel,Earthy
None
Sweet,Flowery,Earthy
Pungent,Lemon,Peach
Sweet,Vanilla
Earthy,Diesel,Chemical
Nutty,Earthy,Chestnut
Earthy,Flowery,Tea
Earthy,Flowery,Woody
Skunk,Woody,Sweet
Earthy,Diesel,Pungent
Flowery,Diesel,Sweet
Earthy,Sweet,Pine
Lemon,Citrus,Sweet
Flowery,Chemical,Spicy/Herbal
Sweet,Flowery,Skunk
Citrus,Skunk
Earthy,Sweet,Woody
Sweet,Pine,Woody
Woody,Pine,Pungent
Tobacc

Citrus,Earthy,Pine
Diesel,Skunk,Pungent
Ammonia,Citrus,Coffee
Citrus,Sweet,Spicy/Herbal
Strawberry,Sweet,Diesel
Sweet,Diesel,Citrus
Citrus,Diesel,Orange
Citrus,Diesel,Sweet
Earthy,Diesel,Flowery
Pungent,Diesel,Sweet
Sweet,Tropical,Pungent
Earthy,Mango,Tropical
Sweet
None
Sweet,Berry,Blueberry
None
Skunk,Mango,Sweet
Lemon
Earthy,Flowery,Berry
Earthy,Sweet,Pungent
Sweet,Citrus,Pine
Sweet,Earthy,Berry
None
Ammonia,Diesel,Spicy/Herbal
Pungent,Pine,Flowery
Earthy,Sweet,Flowery
Sweet,Citrus,Earthy
Earthy,Sweet,Pungent
Pine,Woody,Flowery
Sweet,Berry,Strawberry
Flowery,Lavender,Rose
Sweet,Flowery,Tea
Citrus,Earthy,Sweet
Earthy,Spicy/Herbal,Berry
Berry,Citrus,Sweet
Earthy,Lemon,Pungent
Skunk,Pine,Earthy
Citrus,Sweet,Lemon
Grape,Pine,Menthol
Diesel,Pungent,Earthy
Diesel,Pepper,Earthy
Tropical,Sweet,Pungent
Pine,Pungent,Woody
Berry,Earthy,Pungent
Sweet,Flowery,Berry
Earthy,Woody,Berry
Earthy,Pine,Orange
Sweet,Citrus,Spicy/Herbal
Strawberry,Sweet,Flowery
Strawberry
Strawberry,Sweet,Earthy
Strawber

In [7]:
print(len(total_flavor))
print(max_len)

50
4


In [8]:
print(data["Effects"].isnull().values.sum())
# data["Flavor"] = data["Flavor"].fillna("None")

0


In [9]:
total_effects = []
max_len = 0
for val in data["Effects"].values:
    print(val)
    val = val.split(",")
    
    if len(val) > max_len:
        max_len = len(val)
        
    for e in val:
        if e not in total_effects:
            total_effects.append(e)

Creative,Energetic,Tingly,Euphoric,Relaxed
Relaxed,Aroused,Creative,Happy,Energetic
Uplifted,Happy,Relaxed,Energetic,Creative
Tingly,Creative,Hungry,Relaxed,Uplifted
Happy,Relaxed,Euphoric,Uplifted,Talkative
None
Relaxed,Euphoric,Happy,Uplifted,Hungry
Relaxed,Happy,Euphoric,Uplifted,Giggly
Uplifted,Focused,Happy,Talkative,Relaxed
Relaxed,Tingly,Happy,Euphoric,Uplifted
Energetic,Happy,Talkative,Uplifted
Relaxed,Euphoric,Sleepy,Happy,Talkative
Relaxed,Focused,Euphoric,Uplifted,Aroused
Euphoric,Happy,Uplifted,Talkative,Creative
Relaxed,Uplifted,Happy,Creative,Euphoric
Relaxed,Happy,Euphoric,Giggly,Sleepy
None
Relaxed,Sleepy,Euphoric,Happy,Hungry
Relaxed,Euphoric,Happy,Hungry,Uplifted
Relaxed,Focused,Happy,Sleepy,Uplifted
Relaxed,Happy,Euphoric,Uplifted,Sleepy
Creative,Euphoric,Relaxed,Happy,Hungry
Relaxed,Happy,Uplifted,Focused,Euphoric
Happy,Relaxed,Uplifted,Euphoric,Energetic
Happy,Energetic,Uplifted,Creative,Relaxed
Uplifted,Euphoric,Giggly,Energetic,Sleepy
Relaxed,Euphoric,Sleepy,Happ

Sleepy,Relaxed,Hungry,Uplifted,Happy
Aroused,Talkative,Uplifted,Creative,Euphoric
None
Happy,Focused,Aroused,Sleepy,Tingly
Hungry,Happy,Relaxed,Euphoric,Sleepy
Relaxed,Happy,Euphoric,Uplifted,Aroused
Happy,Relaxed,Euphoric,Focused,Uplifted
Euphoric,Creative,Happy,Focused,Relaxed
Energetic,Euphoric,Creative,Happy,Aroused
Relaxed,Happy,Euphoric,Uplifted,Sleepy
Relaxed,Uplifted,Happy,Focused,Sleepy
Euphoric,Happy,Talkative,Creative,Giggly
Relaxed,Happy,Focused,Uplifted,Hungry
Energetic,Creative,Relaxed,Happy,Uplifted
None
Relaxed,Uplifted,Focused,Happy,Sleepy
Relaxed,Happy,Giggly,Uplifted,Hungry
Focused,Uplifted,Creative,Talkative,Energetic
Relaxed,Happy,Hungry,Creative,Euphoric
Aroused,Talkative,Euphoric,Happy,Relaxed
Energetic,Happy,Talkative,Tingly,Uplifted
Euphoric,Relaxed,Tingly,Happy,Sleepy
Relaxed,Sleepy,Happy,Euphoric,Hungry
Sleepy,Creative,Hungry,Relaxed
Hungry,Aroused,Sleepy,Giggly,Happy
Euphoric,Happy,Uplifted,Energetic,Focused
Relaxed,Sleepy,Giggly,Talkative,Uplifted
None
Happ

In [10]:
print(len(total_effects))
print(max_len)

16
5


# Split the Flavor Column

In [11]:
split_data = data["Flavor"].str.split(",")
split_data = split_data.to_list()
names = ["Flavor_1", "Flavor_2", "Flavor_3", "Flavor_4"]
new_flavor = pd.DataFrame(split_data, columns=names)

In [12]:
new_flavor = new_flavor.fillna("None")

In [13]:
new_flavor["Flavor_4"].isnull().values.sum()

# 2308 values of Flavor_4 column are Null, therefore dropping it.
new_flavor = new_flavor.drop(columns=["Flavor_4"])

new_flavor

Flavor_1 Flavor_2      Flavor_3
0           Earthy    Sweet        Citrus
1          Flowery   Violet        Diesel
2     Spicy/Herbal     Sage         Woody
3          Apricot   Citrus    Grapefruit
4           Citrus   Earthy        Orange
...            ...      ...           ...
2346        Earthy    Woody          Pine
2347         Sweet    Berry         Grape
2348        Earthy    Sweet  Spicy/Herbal
2349         Sweet   Earthy       Pungent
2350         Berry   Earthy       Pungent

[2351 rows x 3 columns]

# Spliting the Effects column

In [17]:
split_data = data["Effects"].str.split(",").to_list()
names = ["Effect_1", "Effect_2", "Effect_3", "Effect_4", "Effect_5"]

new_effect = pd.DataFrame(split_data, columns=names).fillna("None")

In [18]:
new_effect

Effect_1   Effect_2   Effect_3   Effect_4   Effect_5
0     Creative  Energetic     Tingly   Euphoric    Relaxed
1      Relaxed    Aroused   Creative      Happy  Energetic
2     Uplifted      Happy    Relaxed  Energetic   Creative
3       Tingly   Creative     Hungry    Relaxed   Uplifted
4        Happy    Relaxed   Euphoric   Uplifted  Talkative
...        ...        ...        ...        ...        ...
2346     Happy   Uplifted    Relaxed   Euphoric  Energetic
2347   Relaxed      Happy   Euphoric   Uplifted     Sleepy
2348   Relaxed     Sleepy  Talkative   Euphoric      Happy
2349   Relaxed     Sleepy   Euphoric      Happy     Hungry
2350    Hungry    Relaxed   Uplifted      Happy     Sleepy

[2351 rows x 5 columns]

In [16]:
new_effect.describe()

Effect_1 Effect_2  Effect_3  Effect_4  Effect_5
count      2351     2351      2351      2351      2351
unique       15       15        14        14        14
top     Relaxed    Happy  Euphoric  Euphoric  Uplifted
freq        825      571       413       386       273

# Feature Hasher

In [33]:
from sklearn.feature_extraction import FeatureHasher

In [34]:
effect_hasher = FeatureHasher(n_features=3, input_type="string")
x = effect_hasher.fit_transform(total_effects)

In [35]:
print(total_effects)
print(x.toarray())
len(np.unique(x.toarray(), axis=0))

['Creative', 'Energetic', 'Tingly', 'Euphoric', 'Relaxed', 'Aroused', 'Happy', 'Uplifted', 'Hungry', 'Talkative', 'None', 'Giggly', 'Focused', 'Sleepy', 'Dry', 'Mouth']
[[-3.  3.  0.]
 [-2.  3. -2.]
 [-2.  0.  0.]
 [-1.  3. -2.]
 [ 1.  3.  3.]
 [-1.  6.  0.]
 [-2.  2.  1.]
 [-3.  1.  2.]
 [-1.  4. -1.]
 [-2.  0.  1.]
 [-1.  2. -1.]
 [ 0.  1. -1.]
 [-1.  4. -2.]
 [-2.  3.  1.]
 [ 0.  2.  1.]
 [-1.  3. -1.]]


16

In [36]:
flavor_hasher = FeatureHasher(n_features=10, input_type="string")
y = flavor_hasher.fit_transform(total_flavor)

In [37]:
print(total_flavor)
print(y.toarray())
len(np.unique(y.toarray(), axis=0))

['None', 'Earthy', 'Sweet', 'Citrus', 'Flowery', 'Violet', 'Diesel', 'Spicy/Herbal', 'Sage', 'Woody', 'Apricot', 'Grapefruit', 'Orange', 'Pungent', 'Grape', 'Pine', 'Skunk', 'Berry', 'Pepper', 'Menthol', 'Blue', 'Cheese', 'Chemical', 'Mango', 'Lemon', 'Peach', 'Vanilla', 'Nutty', 'Chestnut', 'Tea', 'Tobacco', 'Tropical', 'Strawberry', 'Blueberry', 'Mint', 'Apple', 'Honey', 'Lavender', 'Lime', 'Coffee', 'Ammonia', 'Minty', 'Tree', 'Fruit', 'Butter', 'Pineapple', 'Tar', 'Rose', 'Plum', 'Pear']
[[ 0.  0.  0.  1. -1.  0.  0. -1.  0.  1.]
 [ 1.  0.  0.  0.  1.  0.  0.  1.  0. -1.]
 [ 0. -1.  0.  0.  0.  0.  0.  0. -1.  1.]
 [ 0. -2.  1.  0.  0.  1.  0.  0.  0. -2.]
 [ 0. -1.  1.  1.  1.  1.  0.  0. -1.  1.]
 [ 0. -1.  1.  1.  0.  0.  0.  0.  0.  1.]
 [ 0. -1.  1.  0.  0.  0.  1.  0.  0.  1.]
 [ 1. -2.  1.  0.  1.  1. -1. -1. -1.  3.]
 [ 1.  0. -1.  0.  0.  0.  0.  0. -1.  1.]
 [ 0.  0.  0.  2.  0.  0.  0.  0.  0.  1.]
 [ 0. -1.  1.  1.  0.  1. -1. -1.  0. -1.]
 [ 1. -1.  1.  1.  0.  2. -1. 

50

# Convert flavor and effects to numerical data

In [38]:
total_effects

['Creative',
 'Energetic',
 'Tingly',
 'Euphoric',
 'Relaxed',
 'Aroused',
 'Happy',
 'Uplifted',
 'Hungry',
 'Talkative',
 'None',
 'Giggly',
 'Focused',
 'Sleepy',
 'Dry',
 'Mouth']

In [39]:
names = ["Effect_1", "Effect_2", "Effect_3", "Effect_4", "Effect_5"]
num_effect = pd.DataFrame([])
for name in names:
    d = new_effect[name]
    temp = effect_hasher.transform(d).toarray()
    temp = pd.DataFrame(temp)
    num_effect = pd.concat([num_effect, temp], axis=1)
    

In [40]:
print(num_effect.head(3))
print(new_effect.head(3))

     0    1    2    0    1    2    0    1    2    0    1    2    0    1    2
0 -3.0  3.0  0.0 -2.0  3.0 -2.0 -2.0  0.0  0.0 -1.0  3.0 -2.0  1.0  3.0  3.0
1  1.0  3.0  3.0 -1.0  6.0  0.0 -3.0  3.0  0.0 -2.0  2.0  1.0 -2.0  3.0 -2.0
2 -3.0  1.0  2.0 -2.0  2.0  1.0  1.0  3.0  3.0 -2.0  3.0 -2.0 -3.0  3.0  0.0
   Effect_1   Effect_2  Effect_3   Effect_4   Effect_5
0  Creative  Energetic    Tingly   Euphoric    Relaxed
1   Relaxed    Aroused  Creative      Happy  Energetic
2  Uplifted      Happy   Relaxed  Energetic   Creative


In [41]:
names = ["Flavor_1", "Flavor_2", "Flavor_3"]
num_flavor = pd.DataFrame([])
for name in names:
    d = new_flavor[name]
    temp = flavor_hasher.transform(d).toarray()
    temp = pd.DataFrame(temp)
    num_flavor = pd.concat([num_flavor, temp], axis=1)

In [42]:
num_flavor.head(3)
# print(new_flavor.head(1))

0    1    2    3    4    5    6    7    8    9  ...    0    1    2    3  \
0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0 -1.0  ...  0.0 -2.0  1.0  0.0   
1  0.0 -1.0  1.0  1.0  1.0  1.0  0.0  0.0 -1.0  1.0  ...  0.0 -1.0  1.0  0.0   
2  1.0 -2.0  1.0  0.0  1.0  1.0 -1.0 -1.0 -1.0  3.0  ...  0.0  0.0  0.0  2.0   

     4    5    6    7    8    9  
0  0.0  1.0  0.0  0.0  0.0 -2.0  
1  0.0  0.0  1.0  0.0  0.0  1.0  
2  0.0  0.0  0.0  0.0  0.0  1.0  

[3 rows x 30 columns]

In [43]:
new_data = data.copy()

In [44]:
new_data = pd.get_dummies(new_data, columns=["Type"])
new_data

Strain  Rating                                     Effects  \
0             100-Og     4.0  Creative,Energetic,Tingly,Euphoric,Relaxed   
1     98-White-Widow     4.7    Relaxed,Aroused,Creative,Happy,Energetic   
2               1024     4.4   Uplifted,Happy,Relaxed,Energetic,Creative   
3           13-Dawgs     4.2     Tingly,Creative,Hungry,Relaxed,Uplifted   
4           24K-Gold     4.6   Happy,Relaxed,Euphoric,Uplifted,Talkative   
...              ...     ...                                         ...   
2346         Zeus-Og     4.7   Happy,Uplifted,Relaxed,Euphoric,Energetic   
2347        Zkittlez     4.6      Relaxed,Happy,Euphoric,Uplifted,Sleepy   
2348     Zombie-Kush     5.0     Relaxed,Sleepy,Talkative,Euphoric,Happy   
2349       Zombie-Og     4.4        Relaxed,Sleepy,Euphoric,Happy,Hungry   
2350        Zoom-Pie     4.6        Hungry,Relaxed,Uplifted,Happy,Sleepy   

                         Flavor  \
0           Earthy,Sweet,Citrus   
1         Flowery,Violet,Diesel   
2       Spicy/Herbal,Sage,Woody   
3     Apricot,Citrus,Grapefruit   
4          Citrus,Earthy,Orange   
...                         ...   
2346          Earthy,Woody,Pine   
2347          Sweet,Berry,Grape   
2348  Earthy,Sweet,Spicy/Herbal   
2349       Sweet,Earthy,Pungent   
2350       Berry,Earthy,Pungent   

                                            Description  Type_hybrid  \
0     $100 OG is a 50/50 hybrid strain that packs a ...            1   
1     The ‘98 Aloha White Widow is an especially pot...            1   
2     1024 is a sativa-dominant hybrid bred in Spain...            0   
3     13 Dawgs is a hybrid of G13 and Chemdawg genet...            1   
4     Also known as Kosher Tangie, 24k Gold is a 60%...            1   
...                                                 ...          ...   
2346  Zeus OG is a hybrid cross between Pineapple OG...            1   
2347  Zkittlez is an indica-dominant mix of Grape Ap...            0   
2348  Zombie Kush by Ripper Seeds comes from two dif...            0   
2349  If you’re looking to transform into a flesh-ea...            0   
2350  Zoom Pie (also known as Zombie Pie) is a heavy...            0   

      Type_indica  Type_sativa  
0               0            0  
1               0            0  
2               0            1  
3               0            0  
4               0            0  
...           ...          ...  
2346            0            0  
2347            1            0  
2348            1            0  
2349            1            0  
2350            1            0  

[2351 rows x 8 columns]

In [45]:
new_data = new_data.drop(columns=["Strain", "Effects", "Flavor", "Description"])
new_data = pd.concat([new_data, num_effect, num_flavor], axis=1)
new_data

Rating  Type_hybrid  Type_indica  Type_sativa    0    1    2    0    1  \
0        4.0            1            0            0 -3.0  3.0  0.0 -2.0  3.0   
1        4.7            1            0            0  1.0  3.0  3.0 -1.0  6.0   
2        4.4            0            0            1 -3.0  1.0  2.0 -2.0  2.0   
3        4.2            1            0            0 -2.0  0.0  0.0 -3.0  3.0   
4        4.6            1            0            0 -2.0  2.0  1.0  1.0  3.0   
...      ...          ...          ...          ...  ...  ...  ...  ...  ...   
2346     4.7            1            0            0 -2.0  2.0  1.0 -3.0  1.0   
2347     4.6            0            1            0  1.0  3.0  3.0 -2.0  2.0   
2348     5.0            0            1            0  1.0  3.0  3.0 -2.0  3.0   
2349     4.4            0            1            0  1.0  3.0  3.0 -2.0  3.0   
2350     4.6            0            1            0 -1.0  4.0 -1.0  1.0  3.0   

        2  ...    0    1    2    3    4    5    6    7    8    9  
0    -2.0  ...  0.0 -2.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0 -2.0  
1     0.0  ...  0.0 -1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  
2     1.0  ...  0.0  0.0  0.0  2.0  0.0  0.0  0.0  0.0  0.0  1.0  
3     0.0  ...  1.0 -1.0  1.0  1.0  0.0  2.0 -1.0  0.0  0.0  1.0  
4     3.0  ...  1.0  0.0  0.0  0.0 -1.0  1.0  0.0  0.0  0.0  1.0  
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
2346  2.0  ...  0.0 -2.0  0.0  0.0 -1.0  0.0  0.0  0.0  0.0  1.0  
2347  1.0  ...  1.0  0.0  0.0  0.0  0.0  1.0 -1.0  0.0  0.0  2.0  
2348  1.0  ...  1.0 -2.0  1.0  0.0  1.0  1.0 -1.0 -1.0 -1.0  3.0  
2349  1.0  ...  0.0 -1.0  0.0  0.0 -2.0  0.0  0.0  0.0  0.0  0.0  
2350  3.0  ...  0.0 -1.0  0.0  0.0 -2.0  0.0  0.0  0.0  0.0  0.0  

[2351 rows x 49 columns]

# Modeling

In [ ]:
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from scipy.spatial.distance import cdist 

In [47]:
# Suppose a customer smoked the 100-Og cannabis and like it. So, I took the features of 100-Og and predicted the recommendations.
test_values = [ 4.,  1.,  0.,  0., -3.,  3.,  0., -2.,  3., -2., -2.,  0.,  0.,
       -1.,  3., -2.,  1.,  3.,  3.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,
        1.,  0., -1.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  1.,
        0., -2.,  1.,  0.,  0.,  1.,  0.,  0.,  0., -2.]

In [ ]:
kmeans = KMeans(n_jobs = -1, n_clusters = 30, init='k-means++', max_iter=500)
model = kmeans.fit(new_data)
test_values = np.array(test_values)
test_values = np.reshape(test_values, (1, -1))
model.predict(test_values)

In [ ]:
# KMeans Clustering
# converting the results into a dataframe and plotting them
frame = pd.DataFrame({'Cluster':range(1,100), 'Dist':Dist})
plt.figure(figsize=(50,25))
plt.plot(frame['Cluster'], frame['Dist'], marker='o')
plt.xlabel('Number of clusters')
plt.ylabel('Inertia')

In [46]:
from sklearn.neighbors import NearestNeighbors
nbrs = NearestNeighbors(n_neighbors=5).fit(new_data)

In [54]:
dist, recommends = nbrs.kneighbors([test_values])
print(dist)
print(recommends)

[[0.5        4.69467784 4.82182538 5.48543526 5.56776436]]
[[   0  100   24 2205  487]]


In [57]:
for index in recommends[0]:
    print(data.values[index])

['100-Og' 'hybrid' 4.0 'Creative,Energetic,Tingly,Euphoric,Relaxed'
 'Earthy,Sweet,Citrus'
 '$100 OG is a 50/50 hybrid strain that packs a strong punch. The name supposedly refers to both its strength and high price when it first started showing up in Hollywood. As a plant, $100 OG tends to produce large dark green buds with few stems. Users report a strong body effect of an indica for pain relief with the more alert, cerebral feeling thanks to its sativa side.']
['American-Dream' 'hybrid' 4.7 'Focused,Euphoric,Tingly,Energetic,Relaxed'
 'Earthy,Sweet,Pungent'
 'American Dream by Sensi Seeds is an indica-dominant strain that blends Afghan Skunk with Jamaican and Hawaiian genetics. Its name is charged with meaning, mainly in that this indica represents “honest toil, personal improvement, and enjoying the fruits of one’s labor,” as Sensi Seeds puts it. Earthy and skunky in flavor, American Dream helps you pursue happiness with balanced uplifting, social effects appropriate for day or eve

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
res = cosine_similarity(new_data)
print(res)